name: Package Function - longest-common-subsequence

env:
  NODE_VERSION: 18.x

on:
  push:
    branches: [ main ]
    paths:
      - 'longest-common-subsequence/**'
    workflow_dispatch:

jobs:
  Package:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the latest code
      uses: actions/checkout@v3
    - name: Setup NodeJS
      uses: actions/setup-node@v3
      with:
        node-version: ${{ NODE_VERSION }}
    - name: Install Dependencies
      run: cd longest-common-subsequence; npm install
    - name: Package Function
      run: npm run nfuncm
    - name: Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Build Function
